### ISSUE TITLE
Some apps showed 2 times like youtube 

### ISSUE THREAD

**Issue by CodeWithUsama** [ciitamjadibraheem/UsageStats#1]
![some apps showing 2 times](https://user-images.githubusercontent.com/26227979/110673630-d4f7a400-81f2-11eb-98ae-45a447ea95ec.jpeg)

**Comment by CodeWithUsama** [comment]
Thank you so much brother for help, issue is solved now. 
![WhatsApp Image 2021-03-11 at 18 16 49](https://user-images.githubusercontent.com/26227979/110793738-cb277c80-8296-11eb-8169-1e3fadd23733.jpeg)

**Comment by ciitamjadibraheem** [comment]
you are welcome :) 
The problwm was that we created the sortedMap of the application with key as: getTotalTimeInForeground() and it seems that it can be that same application has different TotalTimeInForeground, so the solution is to have the unique value as a key for the sortedMap, in our case it's getPackageName

so we changed from: 
`SortedMap<Long, UsageStats> mySortedMap = new TreeMap<>();
for (UsageStats usageStats : appList) {
                mySortedMap.put(usageStats.getTotalTimeInForeground(), usageStats);
            }`
 to:
 `Map<String, UsageStats> mySortedMap = new TreeMap<>();
  for (UsageStats usageStats : appList) {
                mySortedMap.put(usageStats.getPackageName(), usageStats);
            }`
            
You can read the discription about the UsageStats and code-documentaion in our blog :) 
 https://ciit.at/android-usagestatsmanager/

**Comment by ciitamjadibraheem** [comment]
> Thank you so much brother for help, issue is solved now.
> ![WhatsApp Image 2021-03-11 at 18 16 49](https://user-images.githubusercontent.com/26227979/110793738-cb277c80-8296-11eb-8169-1e3fadd23733.jpeg)

you are welcome :) 
The problwm was that we created the sortedMap of the application with key as: getTotalTimeInForeground() and it seems that it can be that same application has different TotalTimeInForeground, so the solution is to have the unique value as a key for the sortedMap, in our case it's getPackageName

so we changed from: 
`SortedMap<Long, UsageStats> mySortedMap = new TreeMap<>();
for (UsageStats usageStats : appList) {
                mySortedMap.put(usageStats.getTotalTimeInForeground(), usageStats);
            }`
 to:
 `Map<String, UsageStats> mySortedMap = new TreeMap<>();
  for (UsageStats usageStats : appList) {
                mySortedMap.put(usageStats.getPackageName(), usageStats);
            }`
            
You can read the discription about the UsageStats and code-documentaion in our blog :) 
 https://ciit.at/android-usagestatsmanager/
